version: "3.7"

services:
  mongo:
    image: mongo:4
    container_name: todolist-mongo
    build: ./docker/mongo
    ports:
      - 27017:${MONGO_PORT}
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_REPLSET_ID: ${MONGO_REPLSET_ID}
      MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
      MONGO_ADMIN_PASS: ${MONGO_ADMIN_PASS}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - ./docker/mongo/log:/log
      - ./docker/mongo/data:/data
      - ./docker/mongo/task.json:/data/task.json
    command: --auth --replSet ${MONGO_REPLSET_ID} --smallfiles --oplogSize 128

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
      # - "./docker/rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
