version: "3.7"

services:
  mongo:
    image: mongo:4
    container_name: mongo
    build: ./docker/mongo
    ports:
      - 27017:${MONGO_PORT}
    environment:
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DATABASE: ${MONGO_DATABASE}
      MONGO_REPLSET_ID: ${MONGO_REPLSET_ID}
      MONGO_ADMIN_USER: ${MONGO_ADMIN_USER}
      MONGO_ADMIN_PASS: ${MONGO_ADMIN_PASS}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
    volumes:
      - ./docker/mongo/log:/log
      - ./docker/mongo/data:/data
      - ./docker/mongo/task.json:/data/task.json
    command: --auth --replSet ${MONGO_REPLSET_ID} --smallfiles --oplogSize 128
